// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trglajrtkmquwnuxwckk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyZ2xhanJ0a21xdXdudXh3Y2trIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxMjQ3ODcsImV4cCI6MjA1MTcwMDc4N30.4AToQ0KIy_2XfurcP8S2o32NyLp0cN7qkMdGv8PzXt4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);